# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 16
      uses: actions/setup-java@v4
      with:
        java-version: 16
        distribution: temurin
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew build shadowJar --no-daemon
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AutoPlug-Plugin
        path: build/libs/AutoPlug-Plugin.jar
